// AUTOGENERATED — do not edit by hand.
// Source: client-react/src/styles/tokens.css
// Regenerate: npm run tokens:to-swift

import SwiftUI
#if canImport(UIKit)
import UIKit

extension Color {
    /// Initialize a theme-aware color from light/dark hex literals.
    init(light: String, dark: String) {
        self = Color(UIColor { traits in
            traits.userInterfaceStyle == .dark
                ? UIColor(hex: dark)
                : UIColor(hex: light)
        })
    }
}

extension UIColor {
    fileprivate convenience init(hex: String) {
        let trimmed = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        var value: UInt64 = 0
        Scanner(string: trimmed).scanHexInt64(&value)
        let r, g, b, a: CGFloat
        switch trimmed.count {
        case 3:
            r = CGFloat((value >> 8) & 0xF) / 15; g = CGFloat((value >> 4) & 0xF) / 15; b = CGFloat(value & 0xF) / 15; a = 1
        case 6:
            r = CGFloat((value >> 16) & 0xFF) / 255; g = CGFloat((value >> 8) & 0xFF) / 255; b = CGFloat(value & 0xFF) / 255; a = 1
        case 8:
            r = CGFloat((value >> 24) & 0xFF) / 255; g = CGFloat((value >> 16) & 0xFF) / 255; b = CGFloat((value >> 8) & 0xFF) / 255; a = CGFloat(value & 0xFF) / 255
        default:
            r = 0; g = 0; b = 0; a = 1
        }
        self.init(red: r, green: g, blue: b, alpha: a)
    }
}
#endif

enum DS {
    #if canImport(UIKit)
    enum Color {
        static let accent = SwiftUI.Color(light: "#4f6ef7", dark: "#7fa8ff")
        static let accent2 = SwiftUI.Color(light: "#6983ff", dark: "#5f89ff")
        static let accent3 = SwiftUI.Color(light: "#3b5cdb", dark: "#a0c0ff")
        static let accentSecondary = SwiftUI.Color(light: "#b8892f", dark: "#e0b468")
        static let accentSecondary2 = SwiftUI.Color(light: "#cfa04b", dark: "#c99a45")
        static let accentSecondary3 = SwiftUI.Color(light: "#9a7124", dark: "#f0cd8a")
        static let bg = SwiftUI.Color(light: "#f4f7fb", dark: "#0f1419")
        static let border = SwiftUI.Color(light: "#dbe3ed", dark: "#3a4a5a")
        static let danger = SwiftUI.Color(light: "#e05260", dark: "#ff8a96")
        static let danger2 = SwiftUI.Color(light: "#c94855", dark: "#ef6f7b")
        static let muted = SwiftUI.Color(light: "#6b7280", dark: "#a0a8b3")
        static let mutedLight = SwiftUI.Color(light: "#9ca3af", dark: "#6b7580")
        static let mutedStrong = SwiftUI.Color(light: "#858b93", dark: "#b8bec7")
        static let success = SwiftUI.Color(light: "#2f9e6a", dark: "#5dd99f")
        static let surface = SwiftUI.Color(light: "#ffffff", dark: "#1a232f")
        static let surface2 = SwiftUI.Color(light: "#f8fafc", dark: "#232f3d")
        static let surface3 = SwiftUI.Color(light: "#edf1f5", dark: "#2d3d4d")
        static let text = SwiftUI.Color(light: "#1f2937", dark: "#f1f3f5")
        static let textStrong = SwiftUI.Color(light: "#111827", dark: "#ffffff")
        static let viz1 = SwiftUI.Color(light: "#4f6ef7", dark: "#4f6ef7")
        static let viz2 = SwiftUI.Color(light: "#b8892f", dark: "#b8892f")
        static let viz3 = SwiftUI.Color(light: "#2f9e6a", dark: "#2f9e6a")
        static let viz4 = SwiftUI.Color(light: "#c94855", dark: "#c94855")
        static let viz5 = SwiftUI.Color(light: "#7b5bc7", dark: "#7b5bc7")
        static let viz6 = SwiftUI.Color(light: "#2e7a8a", dark: "#2e7a8a")
        static let vizSeq1 = SwiftUI.Color(light: "#e6ecff", dark: "#e6ecff")
        static let vizSeq2 = SwiftUI.Color(light: "#b8c7ff", dark: "#b8c7ff")
        static let vizSeq3 = SwiftUI.Color(light: "#8aa2ff", dark: "#8aa2ff")
        static let vizSeq4 = SwiftUI.Color(light: "#4f6ef7", dark: "#4f6ef7")
        static let vizSeq5 = SwiftUI.Color(light: "#2a42a8", dark: "#2a42a8")
        static let warning = SwiftUI.Color(light: "#d97706", dark: "#ffb74d")
    }
    #endif

    enum Radius {
        static let r2xl: CGFloat = 24
        static let rFull: CGFloat = 999
        static let rLg: CGFloat = 16
        static let rMd: CGFloat = 12
        static let rSm: CGFloat = 8
        static let rXl: CGFloat = 20
        static let rXs: CGFloat = 4
    }

    enum Spacing {
        static let s0: CGFloat = 2
        static let s1: CGFloat = 4
        static let s1h: CGFloat = 6
        static let s2: CGFloat = 8
        static let s2h: CGFloat = 10
        static let s3: CGFloat = 12
        static let s3h: CGFloat = 14
        static let s4: CGFloat = 16
        static let s5: CGFloat = 24
        static let s6: CGFloat = 32
        static let s7: CGFloat = 40
        static let s8: CGFloat = 48
    }

    enum FontSize {
        static let fsBody: CGFloat = 16
        static let fsLabel: CGFloat = 12
        static let fsLg: CGFloat = 22
        static let fsMd: CGFloat = 18
        static let fsMeta: CGFloat = 13
        static let fsSection: CGFloat = 20
        static let fsXl: CGFloat = 28
        static let fsXs: CGFloat = 11.008
    }
}
